name: servant-api-check
version: "0.1"

ghc-options:
  - -Wall

dependencies:
  - base
  - servant == 0.8.*

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec
      - servant-api-check

  doctest:
    main: Doctest.hs
    source-dirs:
      - test
    dependencies:
      - doctest

  slow:
    main: Invalid.hs
    source-dirs:
      - test
    dependencies:
      - hspec
      - servant-api-check
      - interpolate
      - mockery
      - process
      - directory

library:
  source-dirs:
    - src
